### PR TITLE
change: use exceljs instead

### LINKED ISSUE #62: Find an alternate Excel reading library 🙃
As noted in #61, `read-excel-library` is... problematic. Here are the requirements for a library:

 - [x] runs in the browser
 - [x] does not pull in Node.JS dependencies
 - [x] has TypeScript defintions
 - [x] consumes an ArrayBuffer or a Uint8Array

### PR DESCRIPTION
**Pull request by eddieantonio**
Uses ~~[SheetJS][]~~ [exceljs][] instead of `read-excel-file`. More difficult to use, but it can actually successfully parse an `ArrayBuffer` without dragging in Node dependencies 👍🏼

[SheetJS]: https://github.com/SheetJS/sheetjs
[exceljs]: https://github.com/exceljs/exceljs

Resolves #62

### CODE REVIEW

**Comment by jienius** [comment]
Did you try exceljs? That one doesn't work as well?

**Comment by eddieantonio** [comment]
> Did you try exceljs? That one doesn't work as well?

I did not. Is it easier? I got this one working!

**Comment by eddieantonio** [comment]
> Did you try exceljs? That one doesn't work as well?

Update: please see #64. I'm not sure what I'm doing wrong 😩

**Comment by eddieantonio** [comment]
Thanks to @jienius, I got exceljs working! The code is much simpler too!

**Review by xqiu1 — APPROVED** [review]
LGTM

**Pull request merged**
