### PR TITLE
Docs/uml diagrams

### LINKED ISSUE #121: Create Documentation for Complex Workflows
Create a UML Sequence diagram outlining the workflow for how:
* A excel file is uploaded
* Its values are read and stored in custom data classes (WordList)
* The values are converted into a KMP
* The KMP is downloaded on the client
* The workflow between the client and worker 

Optionally we can create a UML Class Diagram outlining the relationship between all the files in `common` and `worker` as the relationship between them is not clear at first glance.

### PR DESCRIPTION
**Pull request by pranavnarang**
Added UML Sequence Diagrams for the functions to:
* Upload an excel file
* Read values from a Google Sheet

Resolves #121

### CODE REVIEW

**Review by IanSeng — APPROVED** [review]
LGTM. I am just wondering if the `env` file being ignored is to store the environment variable for the google upload functionality?

**Comment by eddieantonio** [comment]
> LGTM. I am just wondering if the `env` file being ignored is to store the environment variable for the google upload functionality?

Yeah, I'm pretty sure it's a leftover from that PR. Strictly speaking, it shouldn't be in _this_ PR but ¯\\\_(ツ)\_/¯

**Review by eddieantonio — CHANGES_REQUESTED** [review]
How did you create these diagrams? Could you please provide the **modifiable source** for these digrams, rather than static PNGs? This will make it easier to go back and update these diagram when things change.

Also, I would prefer to store SVG rather than PNG, as the text is modifiable and clear in an SVG :)

* Typo: "GoogleSheetsInput.svlete" -> "GoogleSheetsInput.svelte"
* I would like to see a clear divide between the app thread and the worker thread.
* Can you clearly denote which returns are synchronous and which are asyncrhonous (promised-based)?

As a personal preference, I like having the leftmost entity in a sequence diagram be the user that initiated the action — after all, an app is supposed to satisfy a user request.

**Comment by eddieantonio** [comment]
> How did you create these diagrams? Could you please provide the **modifiable source** for these digrams, rather than static PNGs? This will make it easier to go back and update these diagram when things change.
> 
> Also, I would prefer to store SVG rather than PNG, as the text is modifiable and clear in an SVG :)
> 
> * Typo: "GoogleSheetsInput.svlete" -> "GoogleSheetsInput.svelte"
> * I would like to see a clear divide between the app thread and the worker thread.
> * Can you clearly denote which returns are synchronous and which are asyncrhonous (promised-based)?
> 
> As a personal preference, I like having the leftmost entity in a sequence diagram be the user that initiated the action — after all, an app is supposed to satisfy a user request.

@pranavnarang: consider using something like https://sequencediagram.org/ to save a text file (modifiable source code) and commit both the `.txt` AND the rendered `.svg` in the repository 👍🏼

**Comment by pranavnarang** [comment]
### Updated PR

* Re-created sequence diagrams using https://sequencediagram.org/
* Added `.txt` and `.svg` files to the UML docs folder
* Labelled each relevant class as part of the `App` or `Worker`
* Added actors to the diagram
* Fixed typo

**Review by eddieantonio — APPROVED** [review]
LGTM! Thanks for doing this!

Seeing it all visuallized like this gives me ideas on how to simiplify things and make things more uniform!

**Pull request merged**
