### PR TITLE
[#113] fix: Try migrating unit tests to Mocha or Jest that run IN A BROWSER ENVIRONMENT

### LINKED ISSUE #113: Try migrating unit tests to Mocha or Jest that run IN A BROWSER ENVIRONMENT
**EDIT**:

To satisfy this, the tests must be able to access and/or mock the following [`WindowOrWorkerGlobalScope `](https://developer.mozilla.org/en-US/docs/Web/API/Window) properties **without the use of mocks**:

 - [x] [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch)
 - [ ] [`indexedDB`](WindowOrWorkerGlobalScope.indexedDB)
 - [x] [`new Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob)
 - [ ] [`File.File()`](https://developer.mozilla.org/en-US/docs/Web/API/File/File)

### PR DESCRIPTION
**Pull request by IanSeng**
# Summary
- Rationale: Although `Jest` has faster performance, but `Mocha` is still arguably the most flexible and scaleable unit testing tool on the market. 
- Implemented `Mocha` unit testing framework and `Chai` assertion library into the project (lol I have no clue why is my coffee mug emoji looks so odd) 
- AVA is retained in the project and the Workflow is currently running both AVA and Mocha unit testing on push. AVA could be safely removed from the project once all test cases are migrated to mocha. 

### Mocha folder 
|-> unit-test
Note: `testing.test.ts` will be removed once we have other testing files 

### Instruction to Run Mocha
- `yarn run test:mocha`

### Resolves 
#113

### CODE REVIEW

**Review by eddieantonio — CHANGES_REQUESTED** [review]
In order to successfully close #113, this must run in the Browser environment. What environment do the Mocha tests run right now? Could you please write a test that accesses the `Blob` and `IndexedDB` constructors, as well as the `fetch()` API?

**Comment by eddieantonio** [comment]
> In order to successfully close #113, this must run in the Browser environment. What environment do the Mocha tests run right now? Could you please write a test that accesses the `Blob` and `IndexedDB` constructors, as well as the `fetch()` API?

Note: I updated the body of #113 to reflect the expectations, as I had originally made that issue without writting a body >.<

**Comment by IanSeng** [comment]
> > In order to successfully close #113, this must run in the Browser environment. What environment do the Mocha tests run right now? Could you please write a test that accesses the `Blob` and `IndexedDB` constructors, as well as the `fetch()` API?
> 
> Note: I updated the body of #113 to reflect the expectations, as I had originally made that issue without writting a body >.<

Hi Eddie, thanks for the update. Yup, I can try testing `blob` and `IndexedDB`, do I need to migrate all existing tests or I can select some `blob` and `IndexedDB` related test cases? Since we currently do not have a `fetch` function in the project (it is in the pr I have created last week), but I will figure some way to do a dummy fetch testing for now before closing #113 .

**Comment by eddieantonio** [comment]
> > > In order to successfully close #113, this must run in the Browser environment. What environment do the Mocha tests run right now? Could you please write a test that accesses the `Blob` and `IndexedDB` constructors, as well as the `fetch()` API?
> > 
> > 
> > Note: I updated the body of #113 to reflect the expectations, as I had originally made that issue without writting a body >.<
> 
> Hi Eddie, thanks for the update. Yup, I can try testing `blob` and `IndexedDB`, do I need to migrate all existing tests or I can select some `blob` and `IndexedDB` related test cases? Since we currently do not have a `fetch` function in the project (it is in the pr I have created last week), but I will figure some way to do a dummy fetch testing for now before closing #113 .

Let's leave migrating tests for a future PR :) Let's just make sure Mocha can run our tests in a browser environment. So I think update the placeholder tests to use `fetch()`. `indexedDB`, and `Blob` — we will delete the placeholder tests in a future PR when we migrate our tests to Mocha.

**Comment by IanSeng** [comment]
Stale PR. We have decided to continue using AVA testing after the investigation of this spike

**Pull request closed without merging**
